### ISSUE TITLE
Passing receipt to logPurchase on Android

### ISSUE THREAD

**Issue by itchingpixels** [SudoPlz/react-native-amplitude-analytics#10]
Hi!

Thanks for this library, we find it really useful!
According to the code, the IAP receipt can be passed to logPurchase on iOS, but not on Android. Is there any reason why logPurchase is not supported on Android that we should be aware of?

Thank you!

**Comment by SudoPlz** [comment]
Hey @itchingpixels ,

no particular reason. Up until that point, I thought that was not supported by the Android SDK, but it looks like [it IS supported](https://github.com/amplitude/Amplitude-Android/blob/f5006dd4f539180cff180239d8f556ea68231259/src/com/amplitude/unity/plugins/AmplitudePlugin.java#L80).

I haven't added that because I'm not using `logRevenue` on my project, but I'll be happy to merge a PR if you take the time to add that functionality, and make sure it's working.

Thanks :)

**Comment by itchingpixels** [comment]
cool, we'll do exactly that! thanks!

**Comment by SudoPlz** [comment]
Perfect, send me a holler whenever you've got anything that you want me to merge.
