### ISSUE TITLE
Trouble building the app

### ISSUE THREAD

**Issue by ravi3693** [SudoPlz/react-native-amplitude-analytics#44]
I'm having trouble in building the app

I'm working with 
react native 0.55.4 
cocoapods 1.5.3 
react-native-firebase 4.2.0

npm i react-native-amplitude-analytics --save
react-native link react-native-amplitude-analytics

added the pod to the podfile:
pod 'Amplitude-iOS', '~> 4.3.1'

![screen shot 2018-10-22 at 6 32 40 pm](https://user-images.githubusercontent.com/10805007/47296947-6883a680-d631-11e8-88f8-bcf27f12c172.png)

**Comment by robvolk** [comment]
I'm trying to add Amplitude to my RN project and getting a similar error: 

```
ld: library not found for -lAmplitude-iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've searched and tried the solutions to manually add and link Amplitude, but no luck.  For context, I'm in the process of ejecting an Expo app.  Any ideas?

**Comment by CapitanRedBeard** [comment]
Similarly if you download the Amplitude-iOS sdk manually and move it to root ios folder I get these build errors on iOS:

**Comment by SudoPlz** [comment]
We're using `pod 'Amplitude-iOS', '~> 4.0.4'` in production right now, but I haven't tried `4.3.1` myself. Others have reported successfully using it though.

When it comes to expo, I have no experience with that at all.

Can you guys let me know what flags you have inside Build Settings -> **Other Linker Flags**?

Those Xcode errors are always super cryptic and weird. It always takes a lot of time for me to figure those out when they happen on my end, but they always make sense in the end.

@robvolk I'd experiment with trying various Header Search paths inside the RNAmplitude project Build Settings that target Amplitude (since you're linking it manually)

@CapitanRedBeard Can you try adding `use_frameworks!` in your pod file and then running `pod install` again?

@ravi3693 Maybe you've tried that many times, but can you try `rm -rf ~/Library/Developer/Xcode/DerivedData` , clean project and try again?

Also this may sound silly on my end, but are you sure you ran `pod install` ?
Also is that all you get as an error? Is there anything above the build command that gives out more info as to why this is happening?

**Comment by CapitanRedBeard** [comment]
Sorry @SudoPlz 	I actually avoided the pod install in favor of a manual setup. I thought it would be relevant info here, but I created a new issue for specifically the non-pod install of the SDK on iOS here: #49

**Comment by waterdoo** [comment]
@ravi3693  I'm running into the exact same issue, but have been able to get Xcode to build by not including RNAmplitudeSDK.xcodeproj in the Xcode project, and not including libRNAmplitudeSDK.a in Linked Frameworks and Libraries.

For context, I used the Cocoapods approach.

Somehow the events are still being sent to Amplitude, but not sure if this is the proper way to do this. @SudoPlz is it necessary to include RNAmplitudeSDK.xcodeproj and libRNAmplitudeSDK.a?

**Comment by SudoPlz** [comment]
Based on the react-native version, `react-native link` behaviour differs. Until 0.58 (I think that was when it changed) it didn't include anything automatically, but from that version and on it can now automatically include those dependencies as pod dependencies.

If you open your Podfile and you see `react-native-amplitude-analytics/ios` in one of your pod dependencies, that means you don't need to manually include it on your project target, cocoapods does it for you.

So the answer is yes and no, depending on the react-native version you were when you ran `react-native link react-native-amplitude-analytics`

**Comment by francisco-mercury** [comment]
Solved by dragging the `Amplitude.xcodeproj` file into the `Libraries` section. Once there, clicking drilldown into Products, dragging `libAmplitude.a` into the `Link Binary With Libraries` section under `Build Phases`.

**Comment by FrankSalad** [comment]
Solved by dragging the `Amplitude.xcodeproj` file from the sdk download into the `Libraries` section. Once there, clicking drilldown into `Products`, dragging `libAmplitude.a` into the `Link Binary With Libraries` section under `Build Phases`.

**Comment by giacomocerquone** [comment]
same problem: "ld: library not found for -lAmplitude-iOS"
Rn 0.60.4
Don't know what to do anymore, tried all solution proposed in this thread.

Any of you could explain which are the limitations of using the js sdk instead of this native one?

**Comment by SudoPlz** [comment]
Guys so this sounds like you're not adding the Amplitude SDK (not react-native-amplitude-analytics) to your project.

You have to have BOTH for this to work.
This library deals with the RN part of things, but we still need to setup the native side of things (iOS or Android Amplitude sdk's), the Readme makes that clear I believe.

Closing this for now because I think this discussion is **not related to the current library** but it relates to the **difficulties of importing iOS Dependencies in react-native projects** in general.

If anyone feels that the documentation of this library is lacking or that we could do anything else to make the lives of developers that are new to react-native easier, please feel free to open a PR or just let me know about it and I'll do my best to help out.

**Comment by giacomocerquone** [comment]
Shit, forgot to comment, I had some xcode particular internal files relative to my project that re-cloning my repo and reinstantiating a build it worked.

Ps. I assure you it has been a strange thing since I constantly removed the build folder, the podfile lock, the installed modules etc. But nothing was workin

**Comment by SudoPlz** [comment]
Got it, no worries buddy, thanks for reporting that.
