### ISSUE TITLE
Doubt about pod install in iOS

### ISSUE THREAD

**Issue by xavieramoros** [SudoPlz/react-native-amplitude-analytics#50]
I have a doubt about why, as stated in the iOS installation docs, we need to add the line:
> pod 'Amplitude-iOS', '~> 4.3.1'

If we follow the installation instructions, we need to do first
> react-native link react-native-amplitude-analytics 

which adds to the pod file the following line:
 >pod 'react-native-amplitude-analytics', :path => '../node_modules/react-native-amplitude-analytics'

In the react-native-amplitude-analytics.podspec file we are already saying that react-native-amplitude-analytics depends on Amplitude-iOS with the following line:
>  s.dependency "Amplitude-iOS", "~> 4.3.1"

So why do we need to modify the Podfile again with pod 'Amplitude-iOS'....?

**Comment by SudoPlz** [comment]
hmm probably for better control over which version of Amplitude you're using.

**Comment by plowman** [comment]
Yeah, I just did a clean install **without** adding the line `pod 'Amplitude-iOS', '~> 4.3.1'` and after running `pod install`, `- Amplitude-iOS (4.3.1)` appears in Podfile.lock, so I think @xavieramoros is correct that adding the step manually is not required.

Maybe the fix here is to separate the "manual installation" steps from the "happy path installation" steps in the readme so that lazy people can do the minimum required?

**Comment by xavieramoros** [comment]
Thanks for the clarification @plowman, I'll close the issue since i was just a doubt. I'm still trying to figure out Pods vs Linking setups in iOS with React Native.
